#!/bin/bash

if [ -z "$NVM_DIR" ]
then
    NVM_DIR="$HOME/.nvm"
fi

. $NVM_DIR/nvm.sh
nvm install
nvm use

set -e

if hash pyenv 2>/dev/null;
then
   echo "using pyenv wrapper"
   pyenv install --skip-existing
   pyenv exec pyvenv env
else
   echo "using pyvenv (Built in python)"
   pyvenv env
fi

env/bin/pip install -r requirements.txt

npm install
npm run build

echo "Getting icons..."
git clone git@github.com:teambox/Free-file-icons static/build/img/temp || echo "already exists"
cp static/build/img/temp/512px/* static/build/img/icons/
rm -rf static/build/img/temp


env/bin/python manage.py collectstatic --noinput
